BrightenCommunities/Controllers/AdminController.cs
#region Includes
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using BrightenCommunities.Models;
using PagedList;

#endregion Includes

namespace BrightenCommunities.Controllers
{
    public class AdminController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;

        // Controllers

        // GET: /Admin/
        [Authorize(Roles = "Administrator")]
        #region public ActionResult Index(string searchStringUserNameOrEmail)
        public ActionResult Index(string searchStringUserNameOrEmail, string currentFilter, int? page)
        {
            try
            {
                int intPage = 1;
                int intPageSize = 5;
                int intTotalPageCount = 0;

                if (searchStringUserNameOrEmail != null)
                {
                    intPage = 1;
                }
                else
                {
                    if (currentFilter != null)
                    {
                        searchStringUserNameOrEmail = currentFilter;
                        intPage = page ?? 1;
                    }
                    else
                    {
                        searchStringUserNameOrEmail = "";
                        intPage = page ?? 1;
                    }
                }

                ViewBag.CurrentFilter = searchStringUserNameOrEmail;

                List<ExpandedUserDTO> col_UserDTO = new List<ExpandedUserDTO>();
                int intSkip = (intPage - 1) * intPageSize;

                intTotalPageCount = UserManager.Users
                    .Where(x => x.UserName.Contains(searchStringUserNameOrEmail))
                    .Count();

                var result = UserManager.Users
                    .Where(x => x.UserName.Contains(searchStringUserNameOrEmail))
                    .OrderBy(x => x.UserName)
                    .Skip(intSkip)
                    .Take(intPageSize)
                    .ToList();

                foreach (var item in result)
                {
                    ExpandedUserDTO objUserDTO = new ExpandedUserDTO();

                    objUserDTO.UserName = item.UserName;
                    objUserDTO.Email = item.Email;
                    objUserDTO.LockoutEndDateUtc = item.LockoutEndDateUtc;

                    col_UserDTO.Add(objUserDTO);
                }

                // Set the number of pages
                var _UserDTOAsIPagedList =
                    new StaticPagedList<ExpandedUserDTO>
                    (
                        col_UserDTO, intPage, intPageSize, intTotalPageCount
                        );

                return View(_UserDTOAsIPagedList);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                List<ExpandedUserDTO> col_UserDTO = new List<ExpandedUserDTO>();

                return View(col_UserDTO.ToPagedList(1, 25));
            }
        }
        #endregion

        // Users *****************************

        // GET: /Admin/Edit/Create 
        [Authorize(Roles = "Administrator")]
        #region public ActionResult Create()
        public ActionResult Create()
        {
            ExpandedUserDTO objExpandedUserDTO = new ExpandedUserDTO();

            ViewBag.Roles = GetAllRolesAsSelectList();

            return View(objExpandedUserDTO);
        }
        #endregion

        // PUT: /Admin/Create
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region public ActionResult Create(ExpandedUserDTO paramExpandedUserDTO)
        public ActionResult Create(ExpandedUserDTO paramExpandedUserDTO)
        {
            try
            {
                if (paramExpandedUserDTO == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var Email = paramExpandedUserDTO.Email.Trim();
                var UserName = paramExpandedUserDTO.Email.Trim();
                var Password = paramExpandedUserDTO.Password.Trim();

                if (Email == "")
                {
                    throw new Exception("No Email");
                }

                if (Password == "")
                {
                    throw new Exception("No Password");
                }

                // UserName is LowerCase of the Email
                UserName = Email.ToLower();

                // Create user

                var objNewAdminUser = new ApplicationUser { UserName = UserName, Email = Email };
                var AdminUserCreateResult = UserManager.Create(objNewAdminUser, Password);

                if (AdminUserCreateResult.Succeeded == true)
                {
                    string strNewRole = Convert.ToString(Request.Form["Roles"]);

                    if (strNewRole != "0")
                    {
                        // Put user in role
                        UserManager.AddToRole(objNewAdminUser.Id, strNewRole);
                    }

                    return Redirect("~/Admin");
                }
                else
                {
                    ViewBag.Roles = GetAllRolesAsSelectList();
                    ModelState.AddModelError(string.Empty,
                        "Error: Failed to create the user. Check password requirements.");
                    return View(paramExpandedUserDTO);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Roles = GetAllRolesAsSelectList();
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                return View("Create");
            }
        }
        #endregion

        // GET: /Admin/Edit/TestUser 
        [Authorize(Roles = "Administrator")]
        #region public ActionResult EditUser(string UserName)
        public ActionResult EditUser(string UserName)
        {
            if (UserName == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpandedUserDTO objExpandedUserDTO = GetUser(UserName);
            if (objExpandedUserDTO == null)
            {
                return HttpNotFound();
            }
            return View(objExpandedUserDTO);
        }
        #endregion

        // PUT: /Admin/EditUser
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region public ActionResult EditUser(ExpandedUserDTO paramExpandedUserDTO)
        public ActionResult EditUser(ExpandedUserDTO paramExpandedUserDTO)
        {
            try
            {
                if (paramExpandedUserDTO == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                ExpandedUserDTO objExpandedUserDTO = UpdateDTOUser(paramExpandedUserDTO);

                if (objExpandedUserDTO == null)
                {
                    return HttpNotFound();
                }

                return Redirect("~/Admin");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                return View("EditUser", GetUser(paramExpandedUserDTO.UserName));
            }
        }
        #endregion

        // DELETE: /Admin/DeleteUser
        [Authorize(Roles = "Administrator")]
        #region public ActionResult DeleteUser(string UserName)
        public ActionResult DeleteUser(string UserName)
        {
            try
            {
                if (UserName == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                if (UserName.ToLower() == this.User.Identity.Name.ToLower())
                {
                    ModelState.AddModelError(
                        string.Empty, "Error: Cannot delete the current user");

                    return View("EditUser");
                }

                ExpandedUserDTO objExpandedUserDTO = GetUser(UserName);

                if (objExpandedUserDTO == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    DeleteUser(objExpandedUserDTO);
                }

                return Redirect("~/Admin");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                return View("EditUser", GetUser(UserName));
            }
        }
        #endregion

        // GET: /Admin/EditRoles/TestUser 
        [Authorize(Roles = "Administrator")]
        #region ActionResult EditRoles(string UserName)
        public ActionResult EditRoles(string UserName)
        {
            if (UserName == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            UserName = UserName.ToLower();

            // Check that we have an actual user
            ExpandedUserDTO objExpandedUserDTO = GetUser(UserName);

            if (objExpandedUserDTO == null)
            {
                return HttpNotFound();
            }

            UserAndRolesDTO objUserAndRolesDTO =
                GetUserAndRoles(UserName);

            return View(objUserAndRolesDTO);
        }
        #endregion

        // PUT: /Admin/EditRoles/TestUser 
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region public ActionResult EditRoles(UserAndRolesDTO paramUserAndRolesDTO)
        public ActionResult EditRoles(UserAndRolesDTO paramUserAndRolesDTO)
        {
            try
            {

BrightenCommunities/Controllers/VolunteersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BrightenCommunities.Models;

namespace BrightenCommunities.Controllers
{
    public class VolunteersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Volunteers
        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            return View(db.Volunteers.ToList());
        }

        // GET: Volunteers/Details/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Volunteers volunteers = db.Volunteers.Find(id);
            if (volunteers == null)
            {
                return HttpNotFound();
            }
            return View(volunteers);
        }

        // GET: Volunteers/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Volunteers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Email,Phone")] Volunteers volunteers)
        {
            if (ModelState.IsValid)
            {
                db.Volunteers.Add(volunteers);
                db.SaveChanges();
                return View();
            }

            return View(volunteers);
        }

        // GET: Volunteers/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Volunteers volunteers = db.Volunteers.Find(id);
            if (volunteers == null)
            {
                return HttpNotFound();
            }
            return View(volunteers);
        }

        // POST: Volunteers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Email,Phone")] Volunteers volunteers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(volunteers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(volunteers);
        }

        // GET: Volunteers/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Volunteers volunteers = db.Volunteers.Find(id);
            if (volunteers == null)
            {
                return HttpNotFound();
            }
            return View(volunteers);
        }

        // POST: Volunteers/Delete/5
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Volunteers volunteers = db.Volunteers.Find(id);
            db.Volunteers.Remove(volunteers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BrightenCommunities/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
}

<div class="row admin">
    <h2>Info</h2>

    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

</div>

BrightenCommunities/Views/Shared/_BlogCreatePartial.cshtml
@model BrightenCommunities.Models.Blogs

@{ Layout = null; }

<!-- Modal -->
<div class="modal fade" id="blogModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal col-centered">
                    <h4>Add Blog</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10 col-centered">
                            @using Microsoft.AspNet.Identity
                            @if (Request.IsAuthenticated)
                            {
                                @Html.HiddenFor(model => model.UserName, new { @Value = User.Identity.GetUserName() })
                                @User.Identity.GetUserName();
                            }
                            else
                            {
                                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            }
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Post, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10 col-centered">
                            @Html.EditorFor(model => model.Post, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                            @Html.ValidationMessageFor(model => model.Post, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

BrightenCommunities/Views/Shared/_BlogPartial.cshtml
@model IEnumerable<BrightenCommunities.Models.Blogs>
@{ Layout = null; }

<div class="row">
    <div class="col-lg-10 col-centered">
        <div class="row">
            <div class="col-xs-6 col-lg-6 blog-label">
                @Html.DisplayNameFor(model => model.UserName)
            </div>
            <div class="col-xs-6 col-lg-6 blog-label">
                @Html.DisplayNameFor(model => model.Post)
            </div>
        </div>
        <div class="row blog">
            @foreach (var item in Model)
            {
                <div class="col-xs-6 col-lg-6">
                    @Html.DisplayFor(modelItem => item.UserName)
                </div>
                <div class="col-xs-6 col-lg-6">
                    @Html.DisplayFor(modelItem => item.Post)
                </div>
            }
        </div>
    </div>
</div>

BrightenCommunities/Views/Shared/_ContactPartial.cshtml
@model BrightenCommunities.Models.EmailFormModel

@{
    Layout = null;
}

@using (Html.BeginForm("Contact","Home", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="row contact m-top-25">
        <div class="col-xs-12 col-sm-10 col-lg-10 col-centered">
            <div class="form-horizontal contact-form">
                <div class="form-group">
                    <div class="col-xs-12 col-md-10 col-lg-9 col-lg-push-2">
                        @Html.LabelFor(m => m.FromName, new { @class = "control-label" })

                        @Html.TextBoxFor(m => m.FromName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.FromName)
                    </div>
                </div>
                <div class="form-group">                    
                    <div class="col-xs-12 col-md-10 col-lg-9 col-lg-push-2">
                        @Html.LabelFor(m => m.FromEmail, new { @class = "control-label" })

                        @Html.TextBoxFor(m => m.FromEmail, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.FromEmail)
                    </div>
                </div>
                <div class="form-group">                    
                    <div class="col-xs-12 col-md-10 col-lg-9 col-lg-push-2">
                        @Html.LabelFor(m => m.Message, new { @class = "control-label" })

                        @Html.TextAreaFor(m => m.Message, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Message)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-lg-push-2">
                        <input type="submit" class="btn btn-default" value="Send" />
                    </div>
                </div>
            </div>
        </div>        
    </div>
}

BrightenCommunities/Views/Shared/_DonatePartial.cshtml
@{
    Layout = null;
}

<ul>
    <li>
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post"  target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="UW29MDBJEEEKJ">
            <button class="btn btn-default donate" type="image" name="submit" alt="PayPal">Donate</button>        
        </form>
    </li>
</ul>

BrightenCommunities/Views/Shared/_Footer.cshtml
@{
    Layout = null;
}

<div class="container-fluid">
    <footer>
            <p class="text-center relative offset-bottom">&copy; @DateTime.Now.Year - Brightening Communities</p>
    </footer>
</div>

BrightenCommunities/Views/Shared/_Header.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<div id="header">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <button class="js-menu menu" type="button">
                <span class="bar"></span>
            </button>          
            <nav>
                <ul>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Volunteer", "Volunteers", "Home")</li>
                    @if (User.IsInRole("Administrator"))
        {
            <li>@Html.ActionLink("Administration", "Index", "Admin")</li>
            <li>@Html.ActionLink("Blogs", "Index", "Blogs")</li>
            <li>@Html.ActionLink("Volunteers Admin", "Index" ,"Volunteers")</li>            
}
                </ul>
                @Html.Partial("_LoginPartial")
                @Html.Partial("_DonatePartial")
            </nav>
        </div>
    </div>
    <div class="container-fluid">
        <div class="banner">
            <div class="col-lg-5 sun">
                <img src="~/Content/images/right_half_sun.png" />
            </div>
            <div class="col-lg-7 banner-text">
                <h1>Brightening <br /><span>Communities</span></h1>
                <h3>one day <br /><span>at a time.</span></h3>
            </div>
        </div>
    </div>
   </div>

BrightenCommunities/Views/Shared/_Layout.cshtml
@{ Layout = null; }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Brightening Communities</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @RenderPage("~/Views/Shared/_Header.cshtml")
    <div class="container body-content">
        @RenderBody()       
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/nav.js")
    @Scripts.Render("~/Scripts/Scripts.js")
    @RenderSection("Scripts", required: false)
</body>
@RenderPage("~/Views/Shared/_Footer.cshtml")
</html>

BrightenCommunities/Views/Shared/_ModalPartial.cshtml
@{ 
    Layout = null;
}

<div class="modal fade contactModal" id="successModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <h4>@ViewBag.Message!</h4>
        </div>
    </div>
</div>

BrightenCommunities/Views/Shared/_VolunteersCreatePartial.cshtml
@model BrightenCommunities.Models.Volunteers

@{ Layout = null;}

<div class="modal fade" id="volunteersModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal col-centered">
                    <h4>Add Volunteer</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10 col-centered">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10 col-centered">
                            @using Microsoft.AspNet.Identity
                            @if (Request.IsAuthenticated)
                            {
                                @User.Identity.GetUserName()
                            }
                            else
                            {
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            }
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10 col-centered">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

BrightenCommunities/Views/Shared/_VolunteersPartial.cshtml
@model IEnumerable<BrightenCommunities.Models.Volunteers>

@{ Layout = null;}


<div class="row">
    <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4 volunteers-label text-center">
        @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4 volunteers-label text-center">
        @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 hide-for-small volunteers-label text-center">
        @Html.DisplayNameFor(model => model.Phone)
    </div>
</div>
<div class="row volunteers">
    @foreach (var item in Model)
    {
        <div class="col-xs-6 col-sm-3 col-md-4 col-lg-4 text-center">
            @Html.DisplayFor(modelItem => item.Name)

        </div>
        <div class="col-xs-6 col-sm-5 col-md-4 col-lg-4 text-center">
            @Html.DisplayFor(modelItem => item.Email)
        </div>
        <div class="col-xs-4 col-sm-3 col-md-4 col-lg-4 hide-for-small text-center">
            @Html.DisplayFor(modelItem => item.Phone)
        </div>}
</div>